### ISSUE TITLE
Making read-only SD card process easier

### ISSUE THREAD

**Issue by scruss** [rosswesleyporter/dqmusicbox#3]
In conversation with @ctyler recently, it seems that making the SD card filesystem read-only is much simpler than the way documented in [instructions](https://github.com/rosswesleyporter/dqmusicbox/blob/master/docs/build_instructions_bamboo.docx?raw=true)

**Comment by rosswesleyporter** [comment]
I'm all for simpler. Any links to the alternate method?

As you saw, the current method acts only on the SD card itself. Which carries the benefit that unplugging the unit acts as a factory reset.

**Comment by ctyler** [comment]
Will write some notes on this when time permits, which probably means first week in Feb.

**Comment by rosswesleyporter** [comment]
Thanks Chris. I'm all for simple. For when you have time, here are a few more notes about the current setup:

- The intent is longevity e.g. avoid SD corruption from unexpected shutdowns during writes.

- Because the software doesn't need to change over time, ROM-ish behaviour is fine. That is, the device does only one thing (plays music) and that music playing doesn't need to change over time.

- Also, the device does not need to be on a network of any kind, thus I'm not so concerned about security updates.

- Uses DietPi & RAM logging to reduce writes

- If the maker chooses, they can enable the TMP_WRITE_PROTECT mode on the SD's card specific data, which effectively write protects the whole card e.g. e.g. every power loss is a factory refresh. But it's a pain the in butt for makers to enable this using the process that I documented (though trivial for me now that I've done it a bunch of times).

**Comment by rosswesleyporter** [comment]
I removed the SD card write-protection steps from the build instructions as there seem to be issues with this in very recent versions of DietPi. It's not a super critical feature as I configured DietPI to reduce the likelihood of SD card corruption as a result of unexpected power loss e.g. by enabling RAM logging. I may later try some additional approaches in DietPi, now that it has explicitly added configuration options for read-only filesystems. But I'll close this specific issue.
